apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`argocd.pangarabbit.com`)
      kind: Rule
      services:
        - name: ms-nginx
          namespace: argocd
          kind: Service
          port: 80